### ISSUE TITLE
Need cssDest dest file

### ISSUE THREAD

**Issue by bazilyuk** [itgalaxy/webfont#189]
I have template file (template: resolvePath(COMMON_DIR, 'markup/common/scss/ico/_ico-template1.scss')) when I build project, that file rewrites. But I need 2 different files, one for template and one generated file. Because If I build project ones with that template I can't build it second time, because that file is rewrote!
Do you have that option?

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by guluws** [comment]
Why don't you just put the template file/generated file in a sub directory?

**Comment by bazilyuk** [comment]
> Why don't you just put the template file/generated file in a sub directory?

What you mean?

**Comment by guluws** [comment]
If I understand it correctly the problem is that you have a template under the following path (f.e.)
`C:\ico\_ico-template1.scss`
and you export/generate the files in
`C:\ico\`

The template of course will be overwritten. So why don't you place your template like this:
`C:\ico\template\_ico-template1.scss`


Btw: Why isn't it a njk file?

**Comment by guluws** [comment]
Another approach:
As I get it right those templates are nunjuck files. So you can set your file extension as you want.
`C:\ico\_ico-template1.scss.njk`
Then the generated file won't overwrite it.

> Although you are free to use any file extension you wish for your Nunjucks template files, the Nunjucks community has adopted .njk.

https://mozilla.github.io/nunjucks/templating.html

**Comment by bazilyuk** [comment]
Thanks that helps
