### ISSUE TITLE
add browser compatability

### ISSUE THREAD

**Issue by TheBotlyNoob** [itgalaxy/webfont#426]

**Comment by jimmyandrade** [comment]
@TheBotlyNoob could you bring more details about this issue? Thanks

**Comment by TheBotlyNoob** [comment]
Make this, but for use client side.

**Comment by jimmyandrade** [comment]
> this, but for use client side.

@TheBotlyNoob Sorry, I still don't understand. Can you bring up an example of what's going on with you, and what would need to be done to bring that browser compatibility?

**Comment by TheBotlyNoob** [comment]
A basic React app to convert fonts client side, make a CSS file, and make HTML showcase, all client-side.

**Comment by TheBotlyNoob** [comment]
@jimmyandrade

**Comment by TheBotlyNoob** [comment]
@jimmyandrade

**Comment by TheBotlyNoob** [comment]
@jimmyandrade

**Comment by jimmyandrade** [comment]
@TheBotlyNoob  As I understand it, you would like webfont to be browser-compatible, so you could create an application in React to create fonts entirely client-side. I can say that this is not possible with the library we currently have, as it depends on some features that are specific to Node.js, on server-side (`fs`, for example).

Alternatively, you could create some API in Node.js that uses webfont internally to generate the fonts, and your application in React would consume that API's endpoint. If you follow this path, I would be happy to know that this possibility has worked.

I take this opportunity to make you an important request:

I've noticed that you've tagged me a few times on this issue. I'm guessing you don't know, but this project has been maintained by me alone, and I'm not able to handle all issues with the response time you might be expecting, as I need to balance my time with my work and personal life.

You know... I'm not here getting paid to work, I have no deadlines to meet, and no open-source project member working for free should be mentioned three times in a row just because I haven't responded to a message in the time you were expecting. Ask yourself how busy this person can be, maybe they are working in another issues, before reaching yours. Thanks.
